{% set name = "ibis-bigquery" %}
{% set version = "2.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ibis-bigquery-{{ version }}.tar.gz
  sha256: d84e5e20baf9e15ce4c7ba1411dd23db699875afec1f6b92187574915bb20b6b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - google-cloud-bigquery >=1.12.0,<3.0.0dev
    - google-cloud-bigquery-storage >=1.0.0,<3.0.0dev
    - ibis-framework >=1.2.0,<3.0.0dev
    - pyarrow >=1.0.0,<5.0.0dev
    - pydata-google-auth
    - python >=3.7
    - sqlalchemy <1.4.0dev

test:
  imports:
    - ibis_bigquery
    - ibis_bigquery.udf
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ibis-project/ibis-bigquery
  summary: Ibis BigQuery backend
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tswast
