{% set name = "ibis-bigquery" %}
{% set version = "2.1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ibis-bigquery-{{ version }}.tar.gz
  sha256: 5eaf7b7f58a785c64fdc7c74c5c256f1dcc5d975e495d9836a67f8b112b3f233

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - ibis-framework-core >=2.0.0,<4.0.0dev
    - db-dtypes >=0.3.0,<2.0.0dev
    - google-cloud-bigquery >=1.12.0,<4.0.0dev
    - google-cloud-bigquery-storage >=1.0.0,<3.0.0dev
    - pyarrow >=1.0.0,<8.0.0dev
    - pydata-google-auth
    - python >=3.7
    # Fixes for transitive deps from Ibis
    - atpublic <3,>=2.3
    - regex <2022.0.0,>=2021.7.6

test:
  imports:
    - ibis_bigquery
    - ibis_bigquery.udf
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ibis-project/ibis-bigquery
  summary: Ibis BigQuery backend
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tswast
