{% set name = "ibis-bigquery" %}
{% set version = "2.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ibis-bigquery-{{ version }}.tar.gz
  sha256: c330864d55cfe22e86b0517aa0620d92be4ccfb0decffb1dff2488ac140db38f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - ibis-framework-core >=2.0.0,<3.0.0dev
    - google-cloud-bigquery >=1.12.0,<3.0.0dev
    - google-cloud-bigquery-storage >=1.0.0,<3.0.0dev
    - pyarrow >=1.0.0,<7.0.0dev
    - pydata-google-auth
    - python >=3.7
    # Fixes for transitive deps from Ibis
    - atpublic <3,>=2.3
    - regex <2022.0.0,>=2021.7.6

test:
  imports:
    - ibis_bigquery
    - ibis_bigquery.udf
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ibis-project/ibis-bigquery
  summary: Ibis BigQuery backend
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tswast
